# Generated by Django 5.1.6 on 2025-02-14 09:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ques_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='questionpaper',
            old_name='q_no',
            new_name='q_id',
        ),
    ]
