# Generated by Django 5.1.6 on 2025-02-21 04:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Trip',
            fields=[
                ('trip_id', models.AutoField(primary_key=True, serialize=False)),
                ('trip_duration', models.DurationField()),
                ('trip_cost', models.IntegerField()),
                ('trip_date', models.DateField()),
                ('trip_passengers', models.IntegerField()),
                ('trip_boarding', models.CharField(max_length=255)),
                ('trip_destination', models.CharField(max_length=255)),
            ],
        ),
    ]
