# Generated by Django 5.1.6 on 2025-02-13 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stocks',
            name='stock_id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
