# Generated by Django 5.1.6 on 2025-02-14 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='school',
            fields=[
                ('schl_id', models.IntegerField(primary_key=True, serialize=False)),
                ('schl_name', models.CharField(max_length=100)),
                ('schl_add', models.CharField(max_length=100)),
                ('schl_fees', models.IntegerField()),
            ],
        ),
    ]
